# Generated by Django 3.1.1 on 2020-09-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Все видео'},
        ),
    ]
